webhook_listener: :5000
build_namespace: bot
commit_author: cluster-loadmaster
commit_email: fmhrit+loadmaster@gmail.com
github_token_file: /etc/maintenance-bot/github-token/token
app_id: 51841
installation_id: 6365451
app_private_key_file: /etc/maintenance-bot/github-private-key/privatekey.pem
storage_host: bot-data-hl-svc.bot.svc.cluster.local:9000
storage_token_secret_name: object-storage-token
artifact_bucket: build-artifact
host_aliases:
  - hostnames: ["registry.f110.dev", "registry.storage.x.f110.dev"]
    ip: 192.168.100.132